### ISSUE TITLE
InvoiceListBuilder exception

### ISSUE THREAD

**Issue by davpsh** [Cybercraft/commerce_smart_invoice#4]
When you'll try to open invoices list (/admin/commerce/invoice) you'll get the exception.
Exception message from the logs:

> RuntimeException: The "commerce_invoice" entity type did not define a "uid" key. in Drupal\entity\QueryAccess\QueryAccessHandlerBase->buildConditions() (line 114 of /var/www/html/web/modules/contrib/entity/src/QueryAccess/QueryAccessHandlerBase.php).
--

**Comment by Cybercraft** [comment]
I'll push a fix for that... I've same error in my use case.
